version: "3.8"

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: crud-jlac-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks:
      - app-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email joseluji223@gmail.com --agree-tos --no-eff-email
      -d jlacdev.es -d www.jlacdev.es"

volumes:
  certbot-etc:
  certbot-www:

networks:
  app-net:
    external: true
